language: java
sudo: false
install: true
addons:
  sonarqube: 
    branches: 
      - 6.1.x
jdk:
  - oraclejdk8
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'