server:
  port: 9100
spring:
  application:
    name: tasks-api
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    metadata-map:
      management.port: ${management.port:9100}