server:
  port: 9000
spring:
  application:
    name: tasks-gateway
zuul:
  ignoredServices: '*'
  routes:
    tasks-api: /api/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    metadata-map:
      management.port: ${management.port:9000}